### ISSUE TITLE
Method signature doesn't match that of jQuery.extend()

### ISSUE THREAD

**Issue by morgant** [cferdinandi/extend#1]
[`jQuery.extend()`](https://api.jquery.com/jquery.extend/) actually merges all objects into the first object (which it returns, for easy chaining). It'd be more consistent if this vanilla JavaScript `extend()` had the same method signature to limit confusion and make it easier for developers to transition to/from code utilizing jQuery more easily.

It's easy to merge into a new object by passing in an empty object (`{}`) as the first object.

**Comment by cferdinandi** [comment]
This doesn't do that on purpose. Sometimes you want a new object.

**Comment by morgant** [comment]
@cferdinandi Thanks for the prompt response! I thought it might be the case that it was a purposeful choice. I know you also have blog topics, other code, etc., using your `extend()` signature, so I fully understand your not wanting to change it.

I also agree on often wanting a new object. I personally find jQuery's solution to that to be easy enough to understand and works well in practice. For example:

    var settings = $.extend({}, defaults, options);

I'll keep my fork matching the `jQuery.extend()` method signature, since I'm using it in a project (maybe a couple). I'll update the README and such to note the divergence from your original implementation.

Thanks again for your articles, code, and other efforts! They are all very much appreciated.

**Comment by cferdinandi** [comment]
Cheers, and sorry for the terse response earlier. I've been getting bombarded with OSS requests lately and am trying to balance responsiveness with detail.

**Comment by morgant** [comment]
@cferdinandi No worries, I took it as succinct, not terse. I clearly tend to be verbose.
